spring:
  datasource:
    url: ENC(b50jR4Se7Fp96Y9sp0bU4vTutjSmUWdLb7npDqW9Qm6FE2nma/h7dfEmbCC9L+xL)
    username: ENC(2OMRFfW6qV+EJGkmM+8DHg==)
    password: ENC(+acLZtSIkxphwaupMf7LQsscP9cxn/KD)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate

  # ENUM Deserializer 대소문자 무시
  jackson:
    mapper:
      accept-case-insensitive-enums: true

jasypt:
  encryptor:
    password: ${PASSWORD}

token:
  secret: ENC(EwRA1TfSuygW/y7UaKFgyTyWELifbHGb/CQrBFE9Tw8LYIxgvcEzDg==)
  access-token-expires-in: 9000  # 15분 : 60(s) x 15(m)
  refresh-token-expires-in: 1209600 # 2주 : 60(s) x 60(m) x 24(h) x 14(d)

custom:
  locale: en_US
  timezone: Asia/Seoul
