spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false # 영속성 컨텍스트의 생존 범위를 트랜잭션 범위로 한정
    properties:
      hibernate:
        default_batch_fetch_size: 1000 # OneToMany 관계 조회 시, 쿼리 한 번으로 최적화
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
  servlet:
    multipart:
      max-file-size: 10MB # 파일 업로드 요청 시, 하나의 파일 크기를 10MB로 제한
      max-request-size: 100MB # 파일 업로드 요청 시, 전체 요청 크기를 100MB로 제한

  # ENUM Deserializer 대소문자 무시
  jackson:
    mapper:
      accept-case-insensitive-enums: true

jasypt:
  encryptor:
    password: ${PASSWORD}

token:
  secret: ENC(Xe8iKP7YUyeuieJwi6NUMnHTYC1Nsh42jYCNQR7hRnekV0YPYkI7gMOr286oRFRsmG3zjOKqucs=)

custom:
  locale: en_US
  timezone: Asia/Seoul
