spring:
  datasource:
    url: ENC(b50jR4Se7Fp96Y9sp0bU4vTutjSmUWdLb7npDqW9Qm6FE2nma/h7dfEmbCC9L+xL)
    username: ENC(2OMRFfW6qV+EJGkmM+8DHg==)
    password: ENC(+acLZtSIkxphwaupMf7LQsscP9cxn/KD)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate

  # ENUM Deserializer 대소문자 무시
  jackson:
    mapper:
      accept-case-insensitive-enums: true

jasypt:
  encryptor:
    password: ${PASSWORD}

token:
  secret: ENC(ZWPxWyobK729VrfW9s8GAqg5yAiHA6Cl7w7P3PQbc9QP9b0BZU0yJLLaRsKZKT45tFwrt/LFNoPeAI6fqRIh5IHDOTtwVEErnRzQsU1zIgIQ/SRzcFA2ZBIQIcgEAAywfbi6GVtRGvykI/W//LsZ1LFVb8WWBRZwc6WrAzxKyUmRrrbUdkl5lGg7FegQHm9W)
  access-token-expiration-time: 9000000  # 15분 : 1000(ms) x 60(s) x 15(m)
  refresh-token-expiration-time: 1209600000 # 2주 : 1000(ms) x 60 (s) x 60(m) x 24(h) x 14(d)
